### ISSUE TITLE
PydanticSchemaGenerationError

### ISSUE THREAD

**Issue by awesomesince96** [oracle-samples/oaim-sandbox#47]
Building and running in container and facing below error :

podman build -t localhost/oaim-sandbox:latest .

Docs that i followed: https://oracle-samples.github.io/oaim-sandbox/walkthrough/index.html

![image](https://github.com/user-attachments/assets/062bd06c-871f-466d-9ad5-ccfa6d78300f)

Please let me know if you need any other info, it's an E4.Flex instance on OCI

**Comment by Caoxuyang** [comment]
+1

**Comment by gotsysdba** [comment]
@awesomesince96 @Caoxuyang thank you for reporting this, it was an issue with the upstream llama-index which has now been bumped.  Please re-install the python venv using the latest requirements.txt file.

**Comment by awesomesince96** [comment]
@gotsysdba can you please provide the steps doing so? I see python steps are usually only used for bare metal, i am using "container installation". This will also be helpful for someone coming across this thread in future. Thank you.
